image: docker

services:
  - docker:dind

variables:
  GIT_SSL_NO_VERIFY: "true"

stages:
  - check

check:
  stage: check
  image: registry.gitlab.com/freterium/freterium-docker-images:ops
  script:
    - danger ci --failOnErrors
  only:
    - merge_requests


